-- ###########################################################################
--  FASE 1 — DDL BASE  (PostgreSQL)
--  Sistema de Gestión y Planificación del Cultivo de Palta Hass
--  Migración SQLite -> PostgreSQL + arquitectura Multi-tenant (SaaS)
--
--  Esta fase crea SOLO la estructura: tablas, llaves foráneas, índices y
--  restricciones de integridad. Las POLÍTICAS RLS van en la Fase 2
--  (02_rls.sql) y la carga de datos en la Fase 3 (03_datos.sql).
--
--  -----------------------------------------------------------------------
--  PATRÓN MULTI-TENANT (Opción A — productor_id denormalizado):
--    Cada tabla del tenant lleva su propia columna productor_id NOT NULL.
--    -> RLS sin JOINs: USING (productor_id = current_setting('app.tenant')).
--
--  INTEGRIDAD ENTRE TENANTS (blindaje sin triggers):
--    Para que un hijo NO pueda pertenecer a un tenant distinto que su padre,
--    cada tabla padre declara  UNIQUE (id, productor_id)  y cada hija usa
--    una FK COMPUESTA  (padre_id, productor_id) -> padre (id, productor_id).
--    Solo las raíces del tenant (finca, campana) referencian a productor
--    directamente; el resto hereda la validación por la cadena de FKs.
--
--  CONVERSIONES DE DIALECTO (SQLite -> PostgreSQL):
--    * INTEGER PRIMARY KEY AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--      (BY DEFAULT, no ALWAYS: permite insertar los IDs antiguos en Fase 3).
--    * DATETIME  -> TIMESTAMP        * BOOLEAN usa TRUE/FALSE (no 1/0)
--    * Dinero (costos)  -> NUMERIC(12,2)
--    * Medidas físicas  -> DOUBLE PRECISION (ha, Tn, lat/lon, clima, riego)
--    * FK con ON DELETE CASCADE donde el modelo declara delete-orphan.
--
--  Ejecutar de una sola vez (orden topológico: padres antes que hijas).
-- ###########################################################################

BEGIN;

-- ===========================================================================
--  1. CAPA SAAS / MULTI-TENANT  (raíz, sin dependencias)
-- ===========================================================================

-- Cliente del SaaS (el "Productor"). Raíz del aislamiento de datos.
CREATE TABLE productor (
    id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial  VARCHAR(100)  NOT NULL,
    ruc_dni           VARCHAR(20)   UNIQUE,
    correo_contacto   VARCHAR(100),
    telefono          VARCHAR(20),
    fecha_registro    TIMESTAMP     NOT NULL DEFAULT NOW(),
    activo            BOOLEAN       NOT NULL DEFAULT TRUE
);

-- Usuarios del sistema. productor_id NULL = Superadmin / Proveedor (yo).
CREATE TABLE usuario (
    id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id     INTEGER,                       -- NULL => SUPERADMIN / Proveedor
    nombre_usuario   VARCHAR(50)   NOT NULL UNIQUE,
    correo           VARCHAR(100)  NOT NULL UNIQUE,
    contrasena_hash  VARCHAR(255)  NOT NULL,
    tipo_usuario     VARCHAR(30)   NOT NULL,        -- SUPERADMIN | CLIENTE_ADMIN | CLIENTE_CAMPO
    activo           BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_usuario_productor
        FOREIGN KEY (productor_id) REFERENCES productor (id) ON DELETE CASCADE,
    CONSTRAINT chk_usuario_tipo
        CHECK (tipo_usuario IN ('SUPERADMIN', 'CLIENTE_ADMIN', 'CLIENTE_CAMPO')),
    -- Un SUPERADMIN no pertenece a ningún productor; el resto sí.
    CONSTRAINT chk_usuario_tenant
        CHECK (
            (tipo_usuario =  'SUPERADMIN' AND productor_id IS NULL)
         OR (tipo_usuario <> 'SUPERADMIN' AND productor_id IS NOT NULL)
        )
);

-- ===========================================================================
--  2. CATÁLOGO COMPARTIDO (NO tenant — sin productor_id, sin RLS)
-- ===========================================================================

-- Módulo 10: proveedores meteorológicos. Iguales para todos los clientes.
CREATE TABLE fuente_datos (
    id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(60)   NOT NULL,
    tipo        VARCHAR(30)   NOT NULL,   -- open_meteo | nasa_power | agera5 | davis | manual
    endpoint    VARCHAR(200),
    resolucion  VARCHAR(60),
    activa      BOOLEAN       NOT NULL DEFAULT TRUE
);

-- ===========================================================================
--  3. RAÍCES DEL TENANT
--     Finca cuelga del productor; la Campaña cuelga de la FINCA (cada finca
--     maneja SUS campañas por separado).
-- ===========================================================================

-- Finca (chacra). Raíz física del tenant.
CREATE TABLE finca (
    id             INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id   INTEGER      NOT NULL,            -- DUEÑO de la finca (tenant)
    nombre         VARCHAR(50)  NOT NULL,
    distrito       VARCHAR(120),
    area_total_ha  DOUBLE PRECISION,
    geometria      TEXT,                             -- GeoJSON del contorno
    centro_lat     DOUBLE PRECISION,
    centro_lon     DOUBLE PRECISION,
    CONSTRAINT fk_finca_productor
        FOREIGN KEY (productor_id) REFERENCES productor (id) ON DELETE CASCADE,
    CONSTRAINT uq_finca_tenant UNIQUE (id, productor_id)      -- destino de FK compuesta
);

-- Campaña agrícola. Pertenece a UNA finca (separada de las de otras fincas).
CREATE TABLE campana (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id  INTEGER      NOT NULL,
    finca_id      INTEGER      NOT NULL,
    nombre        VARCHAR(50)  NOT NULL,
    fecha_inicio  DATE         NOT NULL,
    fecha_fin     DATE         NOT NULL,
    estado        VARCHAR(20)  NOT NULL DEFAULT 'borrador',  -- borrador | activa | cerrada
    CONSTRAINT fk_campana_productor
        FOREIGN KEY (productor_id) REFERENCES productor (id) ON DELETE CASCADE,
    -- FK compuesta: la campaña y su finca deben ser del MISMO productor.
    CONSTRAINT fk_campana_finca
        FOREIGN KEY (finca_id, productor_id)
        REFERENCES finca (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT uq_campana_tenant UNIQUE (id, productor_id),   -- destino de FK compuesta
    CONSTRAINT chk_campana_estado CHECK (estado IN ('borrador', 'activa', 'cerrada')),
    CONSTRAINT chk_campana_fechas CHECK (fecha_fin >= fecha_inicio)
);

-- ===========================================================================
--  4. JERARQUÍA OPERATIVA  (heredan tenant por FK compuesta)
-- ===========================================================================

CREATE TABLE lote (
    id                  INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id        INTEGER      NOT NULL,
    finca_id            INTEGER      NOT NULL,
    nombre              VARCHAR(50)  NOT NULL,
    area_ha             DOUBLE PRECISION NOT NULL,
    variedad            VARCHAR(50)  DEFAULT 'Hass',
    ano_plantacion      INTEGER,
    en_produccion       BOOLEAN      NOT NULL DEFAULT TRUE,
    geometria           TEXT,                         -- GeoJSON Polygon/Point
    latitud             DOUBLE PRECISION,             -- centroide -> API de clima
    longitud            DOUBLE PRECISION,
    fuente_preferida_id INTEGER,
    densidad_plantas_ha DOUBLE PRECISION,             -- marco de plantacion; NULL -> el front usa default 350
    -- La FK compuesta exige que el lote y su finca sean del MISMO productor:
    CONSTRAINT fk_lote_finca
        FOREIGN KEY (finca_id, productor_id)
        REFERENCES finca (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_lote_fuente
        FOREIGN KEY (fuente_preferida_id) REFERENCES fuente_datos (id) ON DELETE SET NULL,
    CONSTRAINT uq_lote_tenant UNIQUE (id, productor_id)
);

-- Tabla puente Lote <-> Campaña. La doble FK compuesta garantiza que el lote
-- y la campaña pertenezcan al mismo productor.
CREATE TABLE lote_campana (
    id            INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id  INTEGER  NOT NULL,
    lote_id       INTEGER  NOT NULL,
    campana_id    INTEGER  NOT NULL,
    en_produccion BOOLEAN  NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_lote_campana UNIQUE (lote_id, campana_id),
    CONSTRAINT fk_lc_lote
        FOREIGN KEY (lote_id, productor_id)
        REFERENCES lote (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_lc_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE
);

-- ===========================================================================
--  5. ENTRADA / SALIDA DEL MODELO ML
-- ===========================================================================

-- 15 variables PREDICTORAS (entrada al modelo).
CREATE TABLE registro_agronomico (
    id           INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id INTEGER  NOT NULL,
    lote_id      INTEGER  NOT NULL,
    campana_id   INTEGER  NOT NULL,
    edad_campo   INTEGER,
    edad_prod    INTEGER,
    riego_m3ha   DOUBLE PRECISION,
    hfrio_19     DOUBLE PRECISION,
    hfrio_14_19  DOUBLE PRECISION,
    hfrio_14     DOUBLE PRECISION,
    hfrio_15     DOUBLE PRECISION,
    hac_20_25    DOUBLE PRECISION,
    hac_25       DOUBLE PRECISION,
    humedad      DOUBLE PRECISION,
    eto          DOUBLE PRECISION,
    t_min        DOUBLE PRECISION,
    t_max        DOUBLE PRECISION,
    t_prom       DOUBLE PRECISION,
    lluvia       DOUBLE PRECISION,
    CONSTRAINT fk_ra_lote
        FOREIGN KEY (lote_id, productor_id)
        REFERENCES lote (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_ra_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT uq_ra_tenant UNIQUE (id, productor_id)   -- destino de variable_override
);

-- SALIDA del modelo (rendimiento predicho).
CREATE TABLE prediccion (
    id                 INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id       INTEGER  NOT NULL,
    lote_id            INTEGER  NOT NULL,
    campana_id         INTEGER  NOT NULL,
    tn_ha_predicho     DOUBLE PRECISION NOT NULL,
    tn_total_predicho  DOUBLE PRECISION,
    nivel_confianza    DOUBLE PRECISION,
    intervalo_p10      DOUBLE PRECISION,             -- rendimiento plausible bajo (percentil 10 del bosque)
    intervalo_p90      DOUBLE PRECISION,             -- rendimiento plausible alto (percentil 90 del bosque)
    fecha              TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_pred_lote
        FOREIGN KEY (lote_id, productor_id)
        REFERENCES lote (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_pred_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE
);

-- Resultado REAL de cosecha (se compara con la predicción).
CREATE TABLE resultado_cosecha (
    id            INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id  INTEGER  NOT NULL,
    lote_id       INTEGER  NOT NULL,
    campana_id    INTEGER  NOT NULL,
    tn_ha_real    DOUBLE PRECISION NOT NULL,
    frutos_arbol  DOUBLE PRECISION,
    peso_fruto    DOUBLE PRECISION,
    fecha_cierre  DATE,
    CONSTRAINT fk_rc_lote
        FOREIGN KEY (lote_id, productor_id)
        REFERENCES lote (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_rc_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE
);

-- ===========================================================================
--  6. PLANIFICACIÓN  (módulos 5–8)
-- ===========================================================================

-- M5: plan de cosecha (uno por campaña).
CREATE TABLE plan_cosecha (
    id             INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id   INTEGER  NOT NULL,
    campana_id     INTEGER  NOT NULL,
    fecha_inicio   DATE     NOT NULL,
    semanas_total  INTEGER  NOT NULL,
    tn_total       DOUBLE PRECISION,
    curva          VARCHAR(20) NOT NULL DEFAULT 'campana',
    CONSTRAINT fk_plan_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT uq_plan_tenant UNIQUE (id, productor_id)
);

-- Semana del plan (unidad que consumen M6, M7 y M8).
CREATE TABLE semana_cosecha (
    id              INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id    INTEGER  NOT NULL,
    plan_id         INTEGER  NOT NULL,
    numero_semana   INTEGER  NOT NULL,
    fecha_inicio    DATE,
    fecha_fin       DATE,
    tn_planificada  DOUBLE PRECISION NOT NULL,
    porcentaje      DOUBLE PRECISION,
    tn_real         DOUBLE PRECISION,                 -- cosecha real registrada (F7); NULL = aún sin registrar
    CONSTRAINT fk_sem_plan
        FOREIGN KEY (plan_id, productor_id)
        REFERENCES plan_cosecha (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT uq_sem_tenant UNIQUE (id, productor_id)
);

-- M6: parámetros de mano de obra (uno por plan).
CREATE TABLE plan_mano_obra (
    id                     INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id           INTEGER  NOT NULL,
    plan_cosecha_id        INTEGER  NOT NULL,
    rendimiento_jornal     DOUBLE PRECISION NOT NULL,   -- Tn/jornal/día
    tam_cuadrilla          INTEGER  NOT NULL,
    cuadrillas_disponibles INTEGER  DEFAULT 0,
    dias_cosecha_semana    INTEGER  DEFAULT 6,
    CONSTRAINT fk_pmo_plan
        FOREIGN KEY (plan_cosecha_id, productor_id)
        REFERENCES plan_cosecha (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT uq_pmo_tenant UNIQUE (id, productor_id)
);

-- Personal requerido por semana.
CREATE TABLE mano_obra_semanal (
    id             INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id   INTEGER  NOT NULL,
    plan_id        INTEGER  NOT NULL,
    semana_id      INTEGER  NOT NULL,
    jornales_req   DOUBLE PRECISION,
    cuadrillas_req INTEGER,
    deficit        INTEGER  DEFAULT 0,
    CONSTRAINT fk_mos_plan
        FOREIGN KEY (plan_id, productor_id)
        REFERENCES plan_mano_obra (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_mos_semana
        FOREIGN KEY (semana_id, productor_id)
        REFERENCES semana_cosecha (id, productor_id) ON DELETE CASCADE
);

-- M7: inventario de materiales (por campaña).
CREATE TABLE inventario (
    id                   INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id         INTEGER  NOT NULL,
    campana_id           INTEGER  NOT NULL,
    material             VARCHAR(50) NOT NULL,        -- jaba | pallet | herramienta | epp
    cantidad_disponible  DOUBLE PRECISION DEFAULT 0,
    unidad               VARCHAR(20),
    consumo_por_tn       DOUBLE PRECISION,
    CONSTRAINT fk_inv_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE
);

-- Requerimiento de materiales por semana.
CREATE TABLE logistica_semanal (
    id                   INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id         INTEGER  NOT NULL,
    semana_id            INTEGER  NOT NULL,
    material             VARCHAR(50) NOT NULL,
    cantidad_requerida   DOUBLE PRECISION,
    deficit              DOUBLE PRECISION DEFAULT 0,
    CONSTRAINT fk_log_semana
        FOREIGN KEY (semana_id, productor_id)
        REFERENCES semana_cosecha (id, productor_id) ON DELETE CASCADE
);

-- M8: parámetros de transporte (uno por plan).
CREATE TABLE plan_transporte (
    id                        INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id              INTEGER  NOT NULL,
    plan_cosecha_id           INTEGER  NOT NULL,
    cap_camion_tn             DOUBLE PRECISION NOT NULL,
    costo_por_viaje           NUMERIC(12,2)    NOT NULL,   -- DINERO -> NUMERIC
    camiones_disponibles      INTEGER  DEFAULT 0,
    viajes_por_camion_semana  INTEGER  DEFAULT 6,
    CONSTRAINT fk_ptr_plan
        FOREIGN KEY (plan_cosecha_id, productor_id)
        REFERENCES plan_cosecha (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT uq_ptr_tenant UNIQUE (id, productor_id)
);

-- Despacho por semana.
CREATE TABLE despacho_semanal (
    id              INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id    INTEGER  NOT NULL,
    plan_id         INTEGER  NOT NULL,
    semana_id       INTEGER  NOT NULL,
    tn_despachadas  DOUBLE PRECISION,
    camiones        INTEGER,
    viajes          INTEGER,
    costo           NUMERIC(12,2),                   -- DINERO -> NUMERIC
    deficit         INTEGER  DEFAULT 0,
    CONSTRAINT fk_des_plan
        FOREIGN KEY (plan_id, productor_id)
        REFERENCES plan_transporte (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_des_semana
        FOREIGN KEY (semana_id, productor_id)
        REFERENCES semana_cosecha (id, productor_id) ON DELETE CASCADE
);

-- ===========================================================================
--  7. MONITOREO  (módulo 9: alertas)
-- ===========================================================================
CREATE TABLE alerta (
    id              INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id    INTEGER  NOT NULL,
    campana_id      INTEGER  NOT NULL,
    semana_id       INTEGER,                          -- nullable: no toda alerta es semanal
    tipo            VARCHAR(50),
    mensaje         VARCHAR(255) NOT NULL,
    modulo_origen   VARCHAR(50),
    severidad       VARCHAR(20)  NOT NULL DEFAULT 'media',  -- baja | media | alta
    fecha_creacion  TIMESTAMP    DEFAULT NOW(),
    estado          VARCHAR(20)  NOT NULL DEFAULT 'activa', -- activa | resuelta
    CONSTRAINT fk_alerta_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE,
    -- semana_id nullable: con MATCH SIMPLE (default), si semana_id es NULL la FK
    -- no se evalúa, justo lo que queremos para alertas no semanales.
    -- ON DELETE SET NULL (semana_id): al borrar la semana, NO tocar productor_id
    -- (que es NOT NULL). Requiere PostgreSQL >= 15. Si usas PG < 15, cámbialo por
    -- ON DELETE CASCADE (borraría la alerta al borrar su semana).
    CONSTRAINT fk_alerta_semana
        FOREIGN KEY (semana_id, productor_id)
        REFERENCES semana_cosecha (id, productor_id) ON DELETE SET NULL (semana_id),
    CONSTRAINT chk_alerta_severidad CHECK (severidad IN ('baja', 'media', 'alta')),
    CONSTRAINT chk_alerta_estado    CHECK (estado IN ('activa', 'resuelta'))
);

-- ===========================================================================
--  8. SINCRONIZACIÓN CLIMÁTICA  (módulo 10)
-- ===========================================================================

-- Log de cada sincronización climática de un lote en una campaña.
CREATE TABLE clima_sync (
    id              INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id    INTEGER  NOT NULL,
    lote_id         INTEGER  NOT NULL,
    campana_id      INTEGER  NOT NULL,
    fuente_id       INTEGER,                          -- catálogo compartido
    ventana_inicio  DATE,
    ventana_fin     DATE,
    fetched_at      TIMESTAMP DEFAULT NOW(),
    status          VARCHAR(20) DEFAULT 'ok',         -- ok | error | stale
    mensaje         TEXT,                             -- detalle de error/fallback (texto libre, puede ser largo)
    CONSTRAINT fk_cs_lote
        FOREIGN KEY (lote_id, productor_id)
        REFERENCES lote (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_campana
        FOREIGN KEY (campana_id, productor_id)
        REFERENCES campana (id, productor_id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_fuente
        FOREIGN KEY (fuente_id) REFERENCES fuente_datos (id) ON DELETE SET NULL
);

-- Override manual de una celda climática del registro.
CREATE TABLE variable_override (
    id           INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productor_id INTEGER  NOT NULL,
    registro_id  INTEGER  NOT NULL,
    var_key      VARCHAR(30) NOT NULL,
    valor        DOUBLE PRECISION,
    motivo       VARCHAR(255),
    fecha        TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_vo_registro
        FOREIGN KEY (registro_id, productor_id)
        REFERENCES registro_agronomico (id, productor_id) ON DELETE CASCADE
);

-- ===========================================================================
--  9. ÍNDICES  (PostgreSQL NO indexa las FK automáticamente)
--     a) productor_id en cada tabla del tenant -> filtro RLS.
--     b) columnas FK -> evita seq-scans en JOINs y en DELETE CASCADE.
-- ===========================================================================

-- (a) Tenant
CREATE INDEX idx_usuario_productor   ON usuario (productor_id);
CREATE INDEX idx_campana_productor   ON campana (productor_id);
CREATE INDEX idx_finca_productor     ON finca (productor_id);
CREATE INDEX idx_lote_productor      ON lote (productor_id);
CREATE INDEX idx_lc_productor        ON lote_campana (productor_id);
CREATE INDEX idx_ra_productor        ON registro_agronomico (productor_id);
CREATE INDEX idx_pred_productor      ON prediccion (productor_id);
CREATE INDEX idx_rc_productor        ON resultado_cosecha (productor_id);
CREATE INDEX idx_plan_productor      ON plan_cosecha (productor_id);
CREATE INDEX idx_sem_productor       ON semana_cosecha (productor_id);
CREATE INDEX idx_pmo_productor       ON plan_mano_obra (productor_id);
CREATE INDEX idx_mos_productor       ON mano_obra_semanal (productor_id);
CREATE INDEX idx_inv_productor       ON inventario (productor_id);
CREATE INDEX idx_log_productor       ON logistica_semanal (productor_id);
CREATE INDEX idx_ptr_productor       ON plan_transporte (productor_id);
CREATE INDEX idx_des_productor       ON despacho_semanal (productor_id);
CREATE INDEX idx_alerta_productor    ON alerta (productor_id);
CREATE INDEX idx_cs_productor        ON clima_sync (productor_id);
CREATE INDEX idx_vo_productor        ON variable_override (productor_id);

-- (b) Llaves foráneas (la columna "hija"; productor_id ya cubre el resto)
CREATE INDEX idx_campana_finca       ON campana (finca_id);
-- Regla de negocio a nivel de motor: A LO SUMO UNA campaña 'activa' por finca.
CREATE UNIQUE INDEX uq_campana_activa_finca ON campana (finca_id) WHERE estado = 'activa';
CREATE INDEX idx_lote_finca          ON lote (finca_id);
CREATE INDEX idx_lote_fuente         ON lote (fuente_preferida_id);
CREATE INDEX idx_lc_lote             ON lote_campana (lote_id);
CREATE INDEX idx_lc_campana          ON lote_campana (campana_id);
CREATE INDEX idx_ra_lote             ON registro_agronomico (lote_id);
CREATE INDEX idx_ra_campana          ON registro_agronomico (campana_id);
CREATE INDEX idx_pred_lote           ON prediccion (lote_id);
CREATE INDEX idx_pred_campana        ON prediccion (campana_id);
CREATE INDEX idx_rc_lote             ON resultado_cosecha (lote_id);
CREATE INDEX idx_rc_campana          ON resultado_cosecha (campana_id);
CREATE INDEX idx_plan_campana        ON plan_cosecha (campana_id);
CREATE INDEX idx_sem_plan            ON semana_cosecha (plan_id);
CREATE INDEX idx_pmo_plan            ON plan_mano_obra (plan_cosecha_id);
CREATE INDEX idx_mos_plan            ON mano_obra_semanal (plan_id);
CREATE INDEX idx_mos_semana          ON mano_obra_semanal (semana_id);
CREATE INDEX idx_inv_campana         ON inventario (campana_id);
CREATE INDEX idx_log_semana          ON logistica_semanal (semana_id);
CREATE INDEX idx_ptr_plan            ON plan_transporte (plan_cosecha_id);
CREATE INDEX idx_des_plan            ON despacho_semanal (plan_id);
CREATE INDEX idx_des_semana          ON despacho_semanal (semana_id);
CREATE INDEX idx_alerta_campana      ON alerta (campana_id);
CREATE INDEX idx_alerta_semana       ON alerta (semana_id);
CREATE INDEX idx_cs_lote             ON clima_sync (lote_id);
CREATE INDEX idx_cs_campana          ON clima_sync (campana_id);
CREATE INDEX idx_cs_fuente           ON clima_sync (fuente_id);
CREATE INDEX idx_vo_registro         ON variable_override (registro_id);

COMMIT;

-- ###########################################################################
--  FIN FASE 1. Siguiente: 02_rls.sql (rol de app + ENABLE/FORCE RLS +
--  políticas por tabla + bypass de SUPERADMIN).
-- ###########################################################################
